### ISSUE TITLE
Relative yearly recurrence

### ISSUE THREAD

**Issue by manuelvanrijn** [fnando/recurrence#28]
I'm not sure if I'm missing the syntax or it isn't support (yet) but I'm trying to create a recurrence for the following case:

> Every **year** on the **second** **Monday** of the month **September**

I've tried the following syntax but it seems it doesn't support `:second` as day argument, although the `every: :month` does?

```ruby
Recurrence.new({:every=>:year, :on=>[:september, :second], :weekday=>:monday})
```

**Comment by glau-isidoro** [comment]
You can use `every: :month` with `interval: 12`.

```ruby
Recurrence.new(every: :month, on: :second, weekday: :monday, starts: '2017-09-11', interval: 12)
```

**Comment by manuelvanrijn** [comment]
@glau-isidoro Thanks this works great!
